### ISSUE TITLE
Voice Recorder

### ISSUE THREAD

**Issue by strexicious** [BuildingXwithJS/proposals#1]
There is no specific reason to why I picked a "Voice Recorder", but I wanted to propose something that's not like a common exercise for programming. I hope you don't find it boring and us viewers actually get to learn something new.

**Comment by yamalight** [comment]
Thanks for the submission! That sounds like a good fit for a stream 👍

**Comment by yamalight** [comment]
Done, code in: https://github.com/BuildingXwithJS/webmedia-demo

**Comment by yamalight** [comment]
Video URL: https://www.youtube.com/watch?v=_XF69WYZOSs
