### ISSUE TITLE
Automation with Puppeteer and Chrome headless

### ISSUE THREAD

**Issue by yamalight** [BuildingXwithJS/proposals#12]
As discussed on twitter. Need to come up with a nice use case for that.

**Comment by FDiskas** [comment]
You can make a css #13 regression tests with this one. 
For example 
1. make a simple webpage with some testable elements
2. Take a screenshot and crop it so only that element would be visible and save it
3. Add some assertion for testing 
4. Compare saved image with modified element 
5. Show the difference

**Comment by yamalight** [comment]
@FDiskas hm, that's a pretty good option. Thanks for suggestion!

**Comment by FDiskas** [comment]
Here is an old example https://github.com/nfq-eta/css-regression-test-example

**Comment by yamalight** [comment]
Code is available at: https://github.com/BuildingXwithJS/puppeteer-examples

**Comment by yamalight** [comment]
Stream VoD is here: https://www.youtube.com/watch?v=TSPVa_PsAEY

**Comment by yamalight** [comment]
Summary video is here: https://youtu.be/OMJGHOw2iog
