### ISSUE TITLE
CSS regression tests

### ISSUE THREAD

**Issue by FDiskas** [BuildingXwithJS/proposals#13]
1. How to test visual differences
1. Build your own service or use browserstack
1. Review available tools

**Comment by yamalight** [comment]
Sure, that sounds interesting!

**Comment by yamalight** [comment]
Code is available at: https://github.com/BuildingXwithJS/puppeteer-examples

**Comment by yamalight** [comment]
Stream VoD is here: https://www.youtube.com/watch?v=TSPVa_PsAEY

**Comment by yamalight** [comment]
Summary video is here: https://youtu.be/OMJGHOw2iog
