### ISSUE TITLE
Adding a feature to exoframe

### ISSUE THREAD

**Issue by FWeinb** [BuildingXwithJS/proposals#15]
I don't know if this is out-of-scope for BxJS but it would be great to see you implement new features in exoframe and see you talk about your ideas with exoframe in general.

**Comment by yamalight** [comment]
That should be easy enough :D

**Comment by yamalight** [comment]
Done

**Comment by yamalight** [comment]
VoD on twitch: https://www.twitch.tv/videos/233746432

**Comment by FWeinb** [comment]
Thanks! Just watched the live stream! It is always interesting to see other developers work on there own projects.

**Comment by yamalight** [comment]
VoD is now on youtube: https://youtu.be/Y74uljSOC6s
