### ISSUE TITLE
React App internalization and localization

### ISSUE THREAD

**Issue by FDiskas** [BuildingXwithJS/proposals#17]
Lets cover the problems like:
1. What is CLDR
1. Language detection ([browser](https://github.com/maxogden/browser-locale) or by [IP](https://dev.maxmind.com/geoip/legacy/geolite/))
1. Pluralization
1. Localization, like dates and prices
1. Internationalization like translations to many languages
1. How to prepare files for translation companies.

**Comment by yamalight** [comment]
Sounds good, thanks 👍

**Comment by yamalight** [comment]
Done in https://github.com/BuildingXwithJS/react-translation-app

**Comment by yamalight** [comment]
VoD is now up on youtube!
https://www.youtube.com/watch?v=Q3qcL8GGQsA
