### ISSUE TITLE
Typings in javascript

### ISSUE THREAD

**Issue by FDiskas** [BuildingXwithJS/proposals#19]
We have two main leaders for this topic: TypeScript and Flow. So lets talk about why and which
SO please cover topics like:
1. Do I need this
1. What it brings (advantages, disadvantages)
1. Differences TypeScript and Flow
1. In Reactjs talk about PropTypes 
1. How to configure IDE
1. The trends and some alternatives to typescript and Flow
1. Why it's important or why not

**Comment by yamalight** [comment]
Sounds good 👍

**Comment by yamalight** [comment]
Code is published here: https://github.com/BuildingXwithJS/bxjs-react-component

**Comment by yamalight** [comment]
Video is up on youtube: https://youtu.be/kD5_Hx-H6Fw
