### ISSUE TITLE
Organizing large javascript codebases

### ISSUE THREAD

**Issue by nhaouari** [BuildingXwithJS/proposals#21]
Could you please talk about the best practices in managing and organizing big javascript projects? 
Many thanks.

**Comment by yamalight** [comment]
that sounds like an interesting topic, thanks 👍

**Comment by yamalight** [comment]
Done in: https://youtu.be/C-q9pORU_kI
(no recap because stream came out to be quite short)

**Comment by da-vaibhav** [comment]
where is source code for this stream ? I can't find it under https://github.com/BuildingXwithJS

**Comment by yamalight** [comment]
@da-vaibhav as I said during livestream - I don't think it makes sense to publish code in this case.

**Comment by da-vaibhav** [comment]
ah...I didn't finish watching it thanks 👍
