### ISSUE TITLE
Windows 10 as dev system.

### ISSUE THREAD

**Issue by GeorgySerga** [BuildingXwithJS/proposals#23]
I know it's a very strange one, but I wasn't able to find any windows 10 reviews from developer perspective, and I think you are the person who could answer: how linux cli actually works inside, how hard/easy it is to setup dev environment, could it be as good as unix based one. What do you miss in the system, would you switch to it from your mac os or not? Opinion of real hardcore user, not cnet review. It could be a little video, or short article, not the whole episode, could be the second part of ide setup issue https://github.com/BuildingXwithJS/proposals/issues/20 as well. Thank you.

**Comment by yamalight** [comment]
Sure, I can do that. Been using win10 for development from time to time, so I should be able to talk about it with some degree of competence 😄

**Comment by yamalight** [comment]
Addressed here (to some extent): https://youtu.be/yQsrQKQVg-k
