### ISSUE TITLE
Setting up your own server

### ISSUE THREAD

**Issue by yamalight** [BuildingXwithJS/proposals#25]
As discussed on discord - would be great to show how to setup your own server, from purchase to docker (possibly exoframe?)

**Comment by daniel08s** [comment]
Yes, that would be really helpful!

**Comment by yamalight** [comment]
- do not user root user
- use [pubkey auth](https://www.digitalocean.com/community/tutorials/how-to-configure-ssh-key-based-authentication-on-a-linux-server)
- setup [fail2ban](https://www.fail2ban.org/)
- setup [docker](https://docker.com/)
- setup [traefik](https://traefik.io/) 
- alternatively - setup [exoframe](https://github.com/exoframejs/exoframe)

**Comment by yamalight** [comment]
Done. Link to livestream soon.

**Comment by yamalight** [comment]
VoD for stream: https://youtu.be/fbnV6CtE6-I

**Comment by yamalight** [comment]
Summary video: https://www.youtube.com/watch?v=GR8-Fgkyzxg
