### ISSUE TITLE
PWA and Service Workers

### ISSUE THREAD

**Issue by dragan-novakovic** [BuildingXwithJS/proposals#26]
PWA's seem interesting, maybe a tutorial on Service Workers, push notification, caching strategies, on a desktop website?

**Comment by yamalight** [comment]
That sounds like fun :)

**Comment by qucode1** [comment]
That sounds great :). I would also love to see a combination of a pwa with graphql as a next step. It seems like there are some challenges with caching graphql requests and there are hardly any resources out there combining the two

**Comment by yamalight** [comment]
Code is published under: https://github.com/BuildingXwithJS/notes-pwa-example
VoD and summary vids are coming!

**Comment by yamalight** [comment]
Twitch VoD can be found here: https://www.twitch.tv/videos/236220800
Currently uploading to Youtube..

**Comment by yamalight** [comment]
VoD on youtube: https://youtu.be/ncnRqh7Mr6w
