### ISSUE TITLE
Make a game

### ISSUE THREAD

**Issue by HappyZombies** [BuildingXwithJS/proposals#29]
Whether it's a simple Roguelike game or a turn based game, doesn't matter! Some sort of simple, straightforward game built in JS. For example, maybe something like this!

 https://github.com/Matthew-Burfield/roguelike-dungeon-crawler 

Granted it might take more than 4 hours I feel. So the game doesn't have to be full featured :)

**Comment by yamalight** [comment]
Sounds like an awesome project. Thanks for the suggestion :)

**Comment by yamalight** [comment]
_Veeeery_ basic version is done here: https://github.com/BuildingXwithJS/basic-phaser-game
Video uploading..

**Comment by yamalight** [comment]
Video is now up on youtube: https://youtu.be/uAng4WaborQ
