### ISSUE TITLE
Review: component-based web development

### ISSUE THREAD

**Issue by genemars** [BuildingXwithJS/proposals#30]
A new light (13kB) library for component-based web development.
It can be used the "old" way, just HTML/CSS and JavaScript without build tools.
Or it can be used also with powerful build tool (zuix-web-starter) that can download all resources used in a page, compress/embed them and generate SPA and PWA.

Source:
https://github.com/genielabs/zuix
Web:
https://genielabs.github.io/zuix

**Comment by yamalight** [comment]
Hey, this looks pretty neat! I'd cover it in [BxJS Weekly](https://github.com/BuildingXwithJS/bxjs-weekly) though - is that OK with you?

**Comment by genemars** [comment]
Awesome =) I follow your podcast since a couple of weeks now.
If you need more resources about zuix.js I also wrote a few articles on dev.to, eg:
https://dev.to/genejams/component-based-web-with-zuixjs-3eha

**Comment by yamalight** [comment]
Got it! Added it to next BxJS list, will close the ticket here :)
