### ISSUE TITLE
Make a background changer with electron.

### ISSUE THREAD

**Issue by bakaou** [BuildingXwithJS/proposals#31]
Should be able to change the desktop background from a folder or remotes galleries at a set interval. The purpose would be to demonstrate how to deal with differences between  os implementations.
You can Choose to uses already existing wallpaper changer binary and just call their CLI or use gyp to compile native addons. Good luck.

**Comment by yamalight** [comment]
As discussed on discord - a bit too simple, can be solved with [this module](https://github.com/sindresorhus/wallpaper).
