### ISSUE TITLE
Testing framework

### ISSUE THREAD

**Issue by rishabhkalra** [BuildingXwithJS/proposals#34]
A bunch of testing frameworks already exist but I'd like to learn how to build something relatively basic, doesn't have to be anywhere nearly as fully featured as some of the popular frameworks like Tape, Jasmine, Mocha to name a few. Aggregating test results into a dashboard or something like that might also be cool.  This could be turned into a multi-part series where we can build additional functionality as we go.

**Comment by yamalight** [comment]
Here's the problem - at the _very_ basic level all testing framework does is:
```js
if (value !== expected) {
  throw new Error(`Expected value to be ${expected}, but got ${value}`);
}
```

But there's so many tiny intricate things around that if (runners, additional validators, env helpers, etc) that it'd take ~10 episodes just to build a basic version of something like [node-tap](https://github.com/tapjs/node-tap).
I don't think it's worth it to be honest. 
If you really want to see how those frameworks are built - read the code for node-tap. It's probably one of the simplest testing frameworks out there and its codebase is relatively small.

So, I'm going to reject this.
