### ISSUE TITLE
custom elements/web components

### ISSUE THREAD

**Issue by FDiskas** [BuildingXwithJS/proposals#35]
### Would be awesome to see some live research on thous topics
1. Tooling
1. pollyfils
1. IE11 support
1. Styling
1. Extending
1. publishing

**Comment by yamalight** [comment]
Sounds good.
Also kinda related to https://github.com/BuildingXwithJS/proposals/issues/28

**Comment by FDiskas** [comment]
Thats probably dublicate, but would be nice to cover thouse use cases.

**Comment by yamalight** [comment]
This is now done (kinda): https://youtu.be/wbMfwcscrfU

**Comment by FDiskas** [comment]
Thanks. Learned allot
