### ISSUE TITLE
LMS

### ISSUE THREAD

**Issue by sriramr98** [BuildingXwithJS/proposals#38]
I want to see how various AWS Services are used to optimise an LMS product in production.
Like:
- Video optimisation for different screen sizes.
- Video streaming using a custom stream mechanism
- Microservices ( Serverless maybe? )
- ReactJS/ React Context + Hooks (No redux )

**Comment by yamalight** [comment]
@sriramr98 thanks for submitting this! it does sound like a pretty fun project, but - that's a bit too much for one proposal.
could you please split it into multiple smaller ones (should be doable in ~1-2h stream)?

**Comment by sriramr98** [comment]
Yeah, I guess that makes sense. My idea was that, if we make this into a tutorial series, it would be advanced enough to help anyone get in with the production workflow of such a complicated application. We could make multiple 1-2hr streams over a period of a month or so. It might be a big project but there's a lot that I think we'll learn with this one series

**Comment by yamalight** [comment]
Closing this as stale. Would still be up for looking at smaller proposals based on this.
