### ISSUE TITLE
Build an app that uses new shiny library XState

### ISSUE THREAD

**Issue by ArcticSpaceFox** [BuildingXwithJS/proposals#40]
XState is a new state management library. Maybe something cool?

**Comment by yamalight** [comment]
Any particular reason for closing your two suggestions? I thought XState looked pretty interesting, just didn't have enough time to dig into them more and say yes/no 🤔

**Comment by ArcticSpaceFox** [comment]
@yamalight sry I thought this repo was not in use after looking at the activity. I hoped for some discussions. I personally love XState for its simplicity and readability. I hope to see this coming in an article or video! I am a beginner-intermediate when it comes to programming, so this would be helpful for understanding it.

**Comment by yamalight** [comment]
@Sm03leBr00t repo is a bit deserted at the moment due to my lack of time, but I do plan to return to it!
XState does indeed look pretty cool, so I'm gonna accept this one :)

**Comment by ArcticSpaceFox** [comment]
I am very happy for the quick response!!! 🎉 I hope that you can do it, I can maybe help you out😁 even though you shouldn't put a dime on my knowledge. I am excited to see how you do it.

**Comment by yamalight** [comment]
Done: https://github.com/BuildingXwithJS/react-xstate-example (video link in readme)
