### ISSUE TITLE
Build a backend API using Prisma

### ISSUE THREAD

**Issue by ArcticSpaceFox** [BuildingXwithJS/proposals#42]
Prisma makes designing data structures for the backend easy. Try it out and you will see :)
https://www.prisma.io/

**Comment by yamalight** [comment]
Seems like there's a lot of interest around it. Will check it out :)

**Comment by ArcticSpaceFox** [comment]
Very cool :100: , 
if you like some help or advice just contact me. Also I recommend switching to Prisma2. It is better and I have found no bugs yet.
Also don't get sick :+1:

**Comment by yamalight** [comment]
Done in https://youtu.be/mxUVBde8mDQ
