### ISSUE TITLE
Your thoughts on face recognising node server

### ISSUE THREAD

**Issue by spoman007** [BuildingXwithJS/proposals#44]
First of all, apologies if this is not the correct place or way to put this.
I have built a small demo of face recognising node server, which analyses face using web cam and recognises using face api js.
It would be really nice to hear your opinion on this
https://github.com/spoman007/face-login-website

Also to understand your view on Machine Learning in Node / JS ecosystem. Where you think it is going, if it has any value etc 😄 

Thank you again!!

**Comment by yamalight** [comment]
@spoman007 neat demo, thanks for sharing! I'll probably include it in the next BxJS Weekly 😄 

Best place for that future things like this would be [my twitter](https://twitter.com/yamalight), or [bxjs discord](https://discord.gg/hnKCXqQ)
