### ISSUE TITLE
Creating a library - reusable package in reactjs

### ISSUE THREAD

**Issue by FDiskas** [BuildingXwithJS/proposals#6]
Please cover the following topics:
1. How to develop library and check it in example app (https://docs.npmjs.com/cli/link)
1. `react` and `react-dom` should be as pear dependency and how to develop library (should i install react as global? or should I add different package.json to npm?)
1. Transpile using (rollup?, babel?, typescript?)
1. Transpile to es and umd and why?
1. Talk about how to get props auto completion in IDE using my library
1. How to automate publishing by releasing new version using `npm version` and CI for publishing to npm
1. Why we need to follow https://semver.org principles
1. Do we need to (have/follow) [commit rules](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit)
1. How to (create/automate) release notes
1. How to not publish source code and other mess in to npm
1. How to check published files are correct (unpkg.com)
1. How to deploy demo page using github pages.
1. How to configure github repo to allow community to grow and work with minimum administration
1. Other best practices 
   1. should I use typescript for my library
   1. do I need create type definitions?
   1. folder structure
   1. how to demo page
   1. how to documentation (generated?)
   1. [contributing guidelines](https://help.github.com/articles/helping-people-contribute-to-your-project/)

**Comment by yamalight** [comment]
Probably would do stuff like github pages in separate vids / livestreams, but overall - good idea. Thanks for submitting!

**Comment by yamalight** [comment]
Code is published here: https://github.com/BuildingXwithJS/bxjs-react-component

**Comment by yamalight** [comment]
Video is up on youtube: https://youtu.be/kD5_Hx-H6Fw

**Comment by FDiskas** [comment]
Thanks
