### ISSUE TITLE
Create a chrome browser extension

### ISSUE THREAD

**Issue by FDiskas** [BuildingXwithJS/proposals#8]
1. Build an hello extension for specific website (e.x. youtube change logo)
1. Do it in [vanilajs](http://vanilla-js.com) or using an framework
1. Compile and publish extension to google
> **NOTE:** Contact me for any help or more info

**Comment by yamalight** [comment]
Sounds good 👍

**Comment by yamalight** [comment]
Done!
VoD on twitch: https://www.twitch.tv/videos/238726769
Code is published here: https://github.com/BuildingXwithJS/markstash-extension
